# Generated by Django 5.1 on 2024-09-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
