# Generated by Django 5.1 on 2024-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfavorite',
            options={'ordering': ['-created']},
        ),
    ]
