# Generated by Django 5.1 on 2024-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
