# Generated by Django 5.1 on 2024-09-07 17:34

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.topic'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
