# Generated by Django 5.1 on 2024-09-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_topic_parent_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='lft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='rght',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='tree_id',
            field=models.IntegerField(default=1),
        ),
    ]
