# Generated by Django 5.1 on 2024-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_topic_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
