# Generated by Django 5.1 on 2024-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_topic_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='issue',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
